print ('Sikeresen kiértél az  aluljáróból, átkeltél a fehér-fekete felfestésen. Ezután a Városháza mentén meglátsz egy hobót, aki kiszúrt téged, kezében egy "Kucci" parfümmel.')
print ('"Szép napot honfitárs, szia uram, parfüm érdekel?"')
print("━━━━━━━━━━━━━━━━━━━━━━━")
1 == print('1 - "Menjen innen maga hobó!!!"')
2 == print('2 - "Sajnálom uram de vágtázok hazafele"')
3 == print('3 - "Add ide a suskád, te hobó!"')
4 == print('4 - "Érdekelne"')
print("━━━━━━━━━━━━━━━━━━━━━━━")